// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAchievements = `-- name: ListAchievements :many
SELECT id, code, title, description, icon, xp_reward, condition_type, condition_value, created_at FROM achievements ORDER BY condition_type, condition_value, code
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.XpReward,
			&i.ConditionType,
			&i.ConditionValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAchievements = `-- name: ListUserAchievements :many
SELECT a.id, a.code, a.title, a.description, a.icon, a.xp_reward, a.condition_type, a.condition_value, a.created_at, ua.unlocked_at
FROM user_achievements ua JOIN achievements a ON a.id = ua.achievement_id
WHERE ua.user_id = $1
ORDER BY ua.unlocked_at DESC
`

type ListUserAchievementsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Icon           string             `json:"icon"`
	XpReward       int32              `json:"xp_reward"`
	ConditionType  string             `json:"condition_type"`
	ConditionValue int32              `json:"condition_value"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UnlockedAt     pgtype.Timestamptz `json:"unlocked_at"`
}

func (q *Queries) ListUserAchievements(ctx context.Context, userID pgtype.UUID) ([]ListUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listUserAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAchievementsRow{}
	for rows.Next() {
		var i ListUserAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.XpReward,
			&i.ConditionType,
			&i.ConditionValue,
			&i.CreatedAt,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
