// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, name, slug, description, instructions, common_mistakes, difficulty, muscle_groups, equipment, video_url, image_url, created_at, updated_at FROM exercises WHERE id = $1
`

func (q *Queries) GetExerciseByID(ctx context.Context, id pgtype.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Instructions,
		&i.CommonMistakes,
		&i.Difficulty,
		&i.MuscleGroups,
		&i.Equipment,
		&i.VideoUrl,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, slug, description, instructions, common_mistakes, difficulty, muscle_groups, equipment, video_url, image_url, created_at, updated_at FROM exercises ORDER BY difficulty, name
`

func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Instructions,
			&i.CommonMistakes,
			&i.Difficulty,
			&i.MuscleGroups,
			&i.Equipment,
			&i.VideoUrl,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
