// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLessonByID = `-- name: GetLessonByID :one
SELECT l.id, l.category_id, l.title, l.slug, l.short_description, l.content, l.video_url, l.image_url, l.difficulty, l.duration_minutes, l.sort_order, l.published, l.created_at, l.updated_at, c.name AS category_name, c.slug AS category_slug
FROM lessons l JOIN lesson_categories c ON c.id = l.category_id
WHERE l.id = $1 AND l.published = true
`

type GetLessonByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	ShortDescription string             `json:"short_description"`
	Content          string             `json:"content"`
	VideoUrl         pgtype.Text        `json:"video_url"`
	ImageUrl         pgtype.Text        `json:"image_url"`
	Difficulty       string             `json:"difficulty"`
	DurationMinutes  int32              `json:"duration_minutes"`
	SortOrder        int32              `json:"sort_order"`
	Published        bool               `json:"published"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CategoryName     string             `json:"category_name"`
	CategorySlug     string             `json:"category_slug"`
}

func (q *Queries) GetLessonByID(ctx context.Context, id pgtype.UUID) (GetLessonByIDRow, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i GetLessonByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.ShortDescription,
		&i.Content,
		&i.VideoUrl,
		&i.ImageUrl,
		&i.Difficulty,
		&i.DurationMinutes,
		&i.SortOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT user_id, lesson_id, completed, progress_percent, completed_at, created_at, updated_at FROM user_lesson_progress WHERE user_id = $1 AND lesson_id = $2
`

type GetLessonProgressParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LessonID pgtype.UUID `json:"lesson_id"`
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (UserLessonProgress, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, arg.UserID, arg.LessonID)
	var i UserLessonProgress
	err := row.Scan(
		&i.UserID,
		&i.LessonID,
		&i.Completed,
		&i.ProgressPercent,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedLessons = `-- name: ListPublishedLessons :many
SELECT l.id, l.category_id, l.title, l.slug, l.short_description, l.content, l.video_url, l.image_url, l.difficulty, l.duration_minutes, l.sort_order, l.published, l.created_at, l.updated_at, c.name AS category_name, c.slug AS category_slug
FROM lessons l JOIN lesson_categories c ON c.id = l.category_id
WHERE l.published = true
ORDER BY c.sort_order, l.sort_order, l.title
`

type ListPublishedLessonsRow struct {
	ID               pgtype.UUID        `json:"id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	ShortDescription string             `json:"short_description"`
	Content          string             `json:"content"`
	VideoUrl         pgtype.Text        `json:"video_url"`
	ImageUrl         pgtype.Text        `json:"image_url"`
	Difficulty       string             `json:"difficulty"`
	DurationMinutes  int32              `json:"duration_minutes"`
	SortOrder        int32              `json:"sort_order"`
	Published        bool               `json:"published"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CategoryName     string             `json:"category_name"`
	CategorySlug     string             `json:"category_slug"`
}

func (q *Queries) ListPublishedLessons(ctx context.Context) ([]ListPublishedLessonsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedLessonsRow{}
	for rows.Next() {
		var i ListPublishedLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.ShortDescription,
			&i.Content,
			&i.VideoUrl,
			&i.ImageUrl,
			&i.Difficulty,
			&i.DurationMinutes,
			&i.SortOrder,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO user_lesson_progress (user_id, lesson_id, completed, progress_percent, completed_at)
VALUES ($1, $2, $3, $4, CASE WHEN $3 THEN NOW() ELSE NULL END)
ON CONFLICT (user_id, lesson_id) DO UPDATE
SET completed = EXCLUDED.completed,
    progress_percent = EXCLUDED.progress_percent,
    completed_at = CASE WHEN EXCLUDED.completed THEN COALESCE(user_lesson_progress.completed_at, NOW()) ELSE NULL END
RETURNING user_id, lesson_id, completed, progress_percent, completed_at, created_at, updated_at
`

type UpsertLessonProgressParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	LessonID        pgtype.UUID `json:"lesson_id"`
	Completed       bool        `json:"completed"`
	ProgressPercent int16       `json:"progress_percent"`
}

func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (UserLessonProgress, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.UserID,
		arg.LessonID,
		arg.Completed,
		arg.ProgressPercent,
	)
	var i UserLessonProgress
	err := row.Scan(
		&i.UserID,
		&i.LessonID,
		&i.Completed,
		&i.ProgressPercent,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
