// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Icon           string             `json:"icon"`
	XpReward       int32              `json:"xp_reward"`
	ConditionType  string             `json:"condition_type"`
	ConditionValue int32              `json:"condition_value"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Exercise struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    string             `json:"description"`
	Instructions   string             `json:"instructions"`
	CommonMistakes string             `json:"common_mistakes"`
	Difficulty     string             `json:"difficulty"`
	MuscleGroups   []string           `json:"muscle_groups"`
	Equipment      []string           `json:"equipment"`
	VideoUrl       pgtype.Text        `json:"video_url"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ExerciseSet struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	ExerciseID      pgtype.UUID        `json:"exercise_id"`
	SetNumber       int16              `json:"set_number"`
	Reps            pgtype.Int2        `json:"reps"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Weight          pgtype.Numeric     `json:"weight"`
	Completed       bool               `json:"completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Lesson struct {
	ID               pgtype.UUID        `json:"id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	ShortDescription string             `json:"short_description"`
	Content          string             `json:"content"`
	VideoUrl         pgtype.Text        `json:"video_url"`
	ImageUrl         pgtype.Text        `json:"image_url"`
	Difficulty       string             `json:"difficulty"`
	DurationMinutes  int32              `json:"duration_minutes"`
	SortOrder        int32              `json:"sort_order"`
	Published        bool               `json:"published"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type LessonCategory struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	UserID              pgtype.UUID        `json:"user_id"`
	DisplayName         string             `json:"display_name"`
	Level               int32              `json:"level"`
	Xp                  int32              `json:"xp"`
	CurrentStreak       int32              `json:"current_streak"`
	LongestStreak       int32              `json:"longest_streak"`
	PreferredDifficulty string             `json:"preferred_difficulty"`
	Timezone            string             `json:"timezone"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Program struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	Difficulty    string             `json:"difficulty"`
	DurationWeeks int32              `json:"duration_weeks"`
	Published     bool               `json:"published"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	TelegramID int64              `json:"telegram_id"`
	Username   pgtype.Text        `json:"username"`
	FirstName  string             `json:"first_name"`
	LastName   pgtype.Text        `json:"last_name"`
	PhotoUrl   pgtype.Text        `json:"photo_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserAchievement struct {
	UserID        pgtype.UUID        `json:"user_id"`
	AchievementID pgtype.UUID        `json:"achievement_id"`
	UnlockedAt    pgtype.Timestamptz `json:"unlocked_at"`
}

type UserExerciseStat struct {
	UserID               pgtype.UUID        `json:"user_id"`
	ExerciseID           pgtype.UUID        `json:"exercise_id"`
	TotalSets            int32              `json:"total_sets"`
	TotalReps            int32              `json:"total_reps"`
	MaxReps              int32              `json:"max_reps"`
	TotalDurationSeconds int64              `json:"total_duration_seconds"`
	MaxDurationSeconds   int32              `json:"max_duration_seconds"`
	LastPerformedAt      pgtype.Timestamptz `json:"last_performed_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type UserLessonProgress struct {
	UserID          pgtype.UUID        `json:"user_id"`
	LessonID        pgtype.UUID        `json:"lesson_id"`
	Completed       bool               `json:"completed"`
	ProgressPercent int16              `json:"progress_percent"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserProgress struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	TotalWorkouts           int32              `json:"total_workouts"`
	TotalCompletedExercises int32              `json:"total_completed_exercises"`
	TotalTrainingSeconds    int64              `json:"total_training_seconds"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Workout struct {
	ID               pgtype.UUID        `json:"id"`
	ProgramID        pgtype.UUID        `json:"program_id"`
	DayNumber        int32              `json:"day_number"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	EstimatedMinutes int32              `json:"estimated_minutes"`
	SortOrder        int32              `json:"sort_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WorkoutExercise struct {
	ID                    pgtype.UUID `json:"id"`
	WorkoutID             pgtype.UUID `json:"workout_id"`
	ExerciseID            pgtype.UUID `json:"exercise_id"`
	Sets                  int16       `json:"sets"`
	TargetReps            pgtype.Int2 `json:"target_reps"`
	TargetDurationSeconds pgtype.Int4 `json:"target_duration_seconds"`
	RestSeconds           int32       `json:"rest_seconds"`
	SortOrder             int32       `json:"sort_order"`
	Notes                 pgtype.Text `json:"notes"`
}

type WorkoutSession struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	WorkoutID       pgtype.UUID        `json:"workout_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Status          string             `json:"status"`
	DurationSeconds int32              `json:"duration_seconds"`
	XpEarned        int32              `json:"xp_earned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
