// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserExerciseStats = `-- name: GetUserExerciseStats :many
SELECT ues.user_id, ues.exercise_id, ues.total_sets, ues.total_reps, ues.max_reps, ues.total_duration_seconds, ues.max_duration_seconds, ues.last_performed_at, ues.updated_at, e.name AS exercise_name, e.slug AS exercise_slug
FROM user_exercise_stats ues
JOIN exercises e ON e.id = ues.exercise_id
WHERE ues.user_id = $1
ORDER BY ues.last_performed_at DESC NULLS LAST
`

type GetUserExerciseStatsRow struct {
	UserID               pgtype.UUID        `json:"user_id"`
	ExerciseID           pgtype.UUID        `json:"exercise_id"`
	TotalSets            int32              `json:"total_sets"`
	TotalReps            int32              `json:"total_reps"`
	MaxReps              int32              `json:"max_reps"`
	TotalDurationSeconds int64              `json:"total_duration_seconds"`
	MaxDurationSeconds   int32              `json:"max_duration_seconds"`
	LastPerformedAt      pgtype.Timestamptz `json:"last_performed_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExerciseName         string             `json:"exercise_name"`
	ExerciseSlug         string             `json:"exercise_slug"`
}

func (q *Queries) GetUserExerciseStats(ctx context.Context, userID pgtype.UUID) ([]GetUserExerciseStatsRow, error) {
	rows, err := q.db.Query(ctx, getUserExerciseStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserExerciseStatsRow{}
	for rows.Next() {
		var i GetUserExerciseStatsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ExerciseID,
			&i.TotalSets,
			&i.TotalReps,
			&i.MaxReps,
			&i.TotalDurationSeconds,
			&i.MaxDurationSeconds,
			&i.LastPerformedAt,
			&i.UpdatedAt,
			&i.ExerciseName,
			&i.ExerciseSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProgress = `-- name: GetUserProgress :one
SELECT up.user_id, up.total_workouts, up.total_completed_exercises, up.total_training_seconds, up.updated_at, p.xp, p.level, p.current_streak, p.longest_streak
FROM user_progress up JOIN profiles p ON p.user_id = up.user_id
WHERE up.user_id = $1
`

type GetUserProgressRow struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	TotalWorkouts           int32              `json:"total_workouts"`
	TotalCompletedExercises int32              `json:"total_completed_exercises"`
	TotalTrainingSeconds    int64              `json:"total_training_seconds"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Xp                      int32              `json:"xp"`
	Level                   int32              `json:"level"`
	CurrentStreak           int32              `json:"current_streak"`
	LongestStreak           int32              `json:"longest_streak"`
}

func (q *Queries) GetUserProgress(ctx context.Context, userID pgtype.UUID) (GetUserProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserProgress, userID)
	var i GetUserProgressRow
	err := row.Scan(
		&i.UserID,
		&i.TotalWorkouts,
		&i.TotalCompletedExercises,
		&i.TotalTrainingSeconds,
		&i.UpdatedAt,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
	)
	return i, err
}

const getWorkoutHistory = `-- name: GetWorkoutHistory :many
SELECT ws.id, ws.user_id, ws.workout_id, ws.started_at, ws.completed_at, ws.status, ws.duration_seconds, ws.xp_earned, ws.created_at, ws.updated_at, w.title AS workout_title, p.name AS program_name
FROM workout_sessions ws
JOIN workouts w ON w.id = ws.workout_id
JOIN programs p ON p.id = w.program_id
WHERE ws.user_id = $1 AND ws.status = 'completed'
ORDER BY ws.started_at DESC
LIMIT $2 OFFSET $3
`

type GetWorkoutHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetWorkoutHistoryRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	WorkoutID       pgtype.UUID        `json:"workout_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Status          string             `json:"status"`
	DurationSeconds int32              `json:"duration_seconds"`
	XpEarned        int32              `json:"xp_earned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WorkoutTitle    string             `json:"workout_title"`
	ProgramName     string             `json:"program_name"`
}

func (q *Queries) GetWorkoutHistory(ctx context.Context, arg GetWorkoutHistoryParams) ([]GetWorkoutHistoryRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkoutHistoryRow{}
	for rows.Next() {
		var i GetWorkoutHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.DurationSeconds,
			&i.XpEarned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkoutTitle,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
