// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, name, slug, description, difficulty, duration_weeks, published, created_at, updated_at FROM programs WHERE id = $1 AND published = true
`

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Difficulty,
		&i.DurationWeeks,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedPrograms = `-- name: ListPublishedPrograms :many
SELECT id, name, slug, description, difficulty, duration_weeks, published, created_at, updated_at FROM programs WHERE published = true ORDER BY difficulty, name
`

func (q *Queries) ListPublishedPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPublishedPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Difficulty,
			&i.DurationWeeks,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
