// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteWorkoutSession(ctx context.Context, arg CompleteWorkoutSessionParams) (WorkoutSession, error)
	CreateExerciseSet(ctx context.Context, arg CreateExerciseSetParams) (ExerciseSet, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error)
	GetExerciseByID(ctx context.Context, id pgtype.UUID) (Exercise, error)
	GetLessonByID(ctx context.Context, id pgtype.UUID) (GetLessonByIDRow, error)
	GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (UserLessonProgress, error)
	GetProgramByID(ctx context.Context, id pgtype.UUID) (Program, error)
	GetTodayWorkout(ctx context.Context) (Workout, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (GetUserByTelegramIDRow, error)
	GetUserExerciseStats(ctx context.Context, userID pgtype.UUID) ([]GetUserExerciseStatsRow, error)
	GetUserProgress(ctx context.Context, userID pgtype.UUID) (GetUserProgressRow, error)
	GetWorkoutByID(ctx context.Context, id pgtype.UUID) (Workout, error)
	GetWorkoutHistory(ctx context.Context, arg GetWorkoutHistoryParams) ([]GetWorkoutHistoryRow, error)
	GetWorkoutSession(ctx context.Context, id pgtype.UUID) (WorkoutSession, error)
	ListAchievements(ctx context.Context) ([]Achievement, error)
	ListExercises(ctx context.Context) ([]Exercise, error)
	ListPublishedLessons(ctx context.Context) ([]ListPublishedLessonsRow, error)
	ListPublishedPrograms(ctx context.Context) ([]Program, error)
	ListUserAchievements(ctx context.Context, userID pgtype.UUID) ([]ListUserAchievementsRow, error)
	ListWorkoutExercises(ctx context.Context, workoutID pgtype.UUID) ([]ListWorkoutExercisesRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (Profile, error)
	UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (UserLessonProgress, error)
}

var _ Querier = (*Queries)(nil)
