// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, display_name, timezone)
VALUES ($1, $2, $3)
RETURNING user_id, display_name, level, xp, current_streak, longest_streak, preferred_difficulty, timezone, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
	Timezone    string      `json:"timezone"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.DisplayName, arg.Timezone)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.PreferredDifficulty,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (telegram_id, username, first_name, last_name, photo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, telegram_id, username, first_name, last_name, photo_url, created_at, updated_at
`

type CreateUserParams struct {
	TelegramID int64       `json:"telegram_id"`
	Username   pgtype.Text `json:"username"`
	FirstName  string      `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	PhotoUrl   pgtype.Text `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TelegramID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.telegram_id, u.username, u.first_name, u.last_name, u.photo_url, u.created_at, u.updated_at, p.display_name, p.level, p.xp, p.current_streak, p.longest_streak, p.preferred_difficulty, p.timezone
FROM users u JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TelegramID          int64              `json:"telegram_id"`
	Username            pgtype.Text        `json:"username"`
	FirstName           string             `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	PhotoUrl            pgtype.Text        `json:"photo_url"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DisplayName         string             `json:"display_name"`
	Level               int32              `json:"level"`
	Xp                  int32              `json:"xp"`
	CurrentStreak       int32              `json:"current_streak"`
	LongestStreak       int32              `json:"longest_streak"`
	PreferredDifficulty string             `json:"preferred_difficulty"`
	Timezone            string             `json:"timezone"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.PreferredDifficulty,
		&i.Timezone,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT u.id, u.telegram_id, u.username, u.first_name, u.last_name, u.photo_url, u.created_at, u.updated_at, p.display_name, p.level, p.xp, p.current_streak, p.longest_streak, p.preferred_difficulty, p.timezone
FROM users u JOIN profiles p ON p.user_id = u.id
WHERE u.telegram_id = $1
`

type GetUserByTelegramIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TelegramID          int64              `json:"telegram_id"`
	Username            pgtype.Text        `json:"username"`
	FirstName           string             `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	PhotoUrl            pgtype.Text        `json:"photo_url"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DisplayName         string             `json:"display_name"`
	Level               int32              `json:"level"`
	Xp                  int32              `json:"xp"`
	CurrentStreak       int32              `json:"current_streak"`
	LongestStreak       int32              `json:"longest_streak"`
	PreferredDifficulty string             `json:"preferred_difficulty"`
	Timezone            string             `json:"timezone"`
}

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (GetUserByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i GetUserByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.PreferredDifficulty,
		&i.Timezone,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE profiles
SET display_name = $2, preferred_difficulty = $3, timezone = $4
WHERE user_id = $1
RETURNING user_id, display_name, level, xp, current_streak, longest_streak, preferred_difficulty, timezone, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	DisplayName         string      `json:"display_name"`
	PreferredDifficulty string      `json:"preferred_difficulty"`
	Timezone            string      `json:"timezone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.PreferredDifficulty,
		arg.Timezone,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Level,
		&i.Xp,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.PreferredDifficulty,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
