// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeWorkoutSession = `-- name: CompleteWorkoutSession :one
UPDATE workout_sessions
SET status = 'completed', completed_at = NOW(), duration_seconds = $2, xp_earned = $3
WHERE id = $1 AND status = 'started'
RETURNING id, user_id, workout_id, started_at, completed_at, status, duration_seconds, xp_earned, created_at, updated_at
`

type CompleteWorkoutSessionParams struct {
	ID              pgtype.UUID `json:"id"`
	DurationSeconds int32       `json:"duration_seconds"`
	XpEarned        int32       `json:"xp_earned"`
}

func (q *Queries) CompleteWorkoutSession(ctx context.Context, arg CompleteWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, completeWorkoutSession, arg.ID, arg.DurationSeconds, arg.XpEarned)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.DurationSeconds,
		&i.XpEarned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExerciseSet = `-- name: CreateExerciseSet :one
INSERT INTO exercise_sets (session_id, exercise_id, set_number, reps, duration_seconds, weight, completed)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, session_id, exercise_id, set_number, reps, duration_seconds, weight, completed, created_at, updated_at
`

type CreateExerciseSetParams struct {
	SessionID       pgtype.UUID    `json:"session_id"`
	ExerciseID      pgtype.UUID    `json:"exercise_id"`
	SetNumber       int16          `json:"set_number"`
	Reps            pgtype.Int2    `json:"reps"`
	DurationSeconds pgtype.Int4    `json:"duration_seconds"`
	Weight          pgtype.Numeric `json:"weight"`
	Completed       bool           `json:"completed"`
}

func (q *Queries) CreateExerciseSet(ctx context.Context, arg CreateExerciseSetParams) (ExerciseSet, error) {
	row := q.db.QueryRow(ctx, createExerciseSet,
		arg.SessionID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.DurationSeconds,
		arg.Weight,
		arg.Completed,
	)
	var i ExerciseSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Reps,
		&i.DurationSeconds,
		&i.Weight,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkoutSession = `-- name: CreateWorkoutSession :one
INSERT INTO workout_sessions (user_id, workout_id)
VALUES ($1, $2)
RETURNING id, user_id, workout_id, started_at, completed_at, status, duration_seconds, xp_earned, created_at, updated_at
`

type CreateWorkoutSessionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	WorkoutID pgtype.UUID `json:"workout_id"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, createWorkoutSession, arg.UserID, arg.WorkoutID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.DurationSeconds,
		&i.XpEarned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodayWorkout = `-- name: GetTodayWorkout :one
SELECT w.id, w.program_id, w.day_number, w.title, w.description, w.estimated_minutes, w.sort_order, w.created_at, w.updated_at
FROM workouts w
JOIN programs p ON p.id = w.program_id
WHERE p.published = true
ORDER BY p.difficulty, w.day_number
LIMIT 1
`

func (q *Queries) GetTodayWorkout(ctx context.Context) (Workout, error) {
	row := q.db.QueryRow(ctx, getTodayWorkout)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.DayNumber,
		&i.Title,
		&i.Description,
		&i.EstimatedMinutes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, program_id, day_number, title, description, estimated_minutes, sort_order, created_at, updated_at FROM workouts WHERE id = $1
`

func (q *Queries) GetWorkoutByID(ctx context.Context, id pgtype.UUID) (Workout, error) {
	row := q.db.QueryRow(ctx, getWorkoutByID, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.DayNumber,
		&i.Title,
		&i.Description,
		&i.EstimatedMinutes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSession = `-- name: GetWorkoutSession :one
SELECT id, user_id, workout_id, started_at, completed_at, status, duration_seconds, xp_earned, created_at, updated_at FROM workout_sessions WHERE id = $1
`

func (q *Queries) GetWorkoutSession(ctx context.Context, id pgtype.UUID) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getWorkoutSession, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.DurationSeconds,
		&i.XpEarned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkoutExercises = `-- name: ListWorkoutExercises :many
SELECT we.id, we.workout_id, we.exercise_id, we.sets, we.target_reps, we.target_duration_seconds, we.rest_seconds, we.sort_order, we.notes, e.name AS exercise_name, e.slug AS exercise_slug, e.difficulty AS exercise_difficulty
FROM workout_exercises we
JOIN exercises e ON e.id = we.exercise_id
WHERE we.workout_id = $1
ORDER BY we.sort_order, e.name
`

type ListWorkoutExercisesRow struct {
	ID                    pgtype.UUID `json:"id"`
	WorkoutID             pgtype.UUID `json:"workout_id"`
	ExerciseID            pgtype.UUID `json:"exercise_id"`
	Sets                  int16       `json:"sets"`
	TargetReps            pgtype.Int2 `json:"target_reps"`
	TargetDurationSeconds pgtype.Int4 `json:"target_duration_seconds"`
	RestSeconds           int32       `json:"rest_seconds"`
	SortOrder             int32       `json:"sort_order"`
	Notes                 pgtype.Text `json:"notes"`
	ExerciseName          string      `json:"exercise_name"`
	ExerciseSlug          string      `json:"exercise_slug"`
	ExerciseDifficulty    string      `json:"exercise_difficulty"`
}

func (q *Queries) ListWorkoutExercises(ctx context.Context, workoutID pgtype.UUID) ([]ListWorkoutExercisesRow, error) {
	rows, err := q.db.Query(ctx, listWorkoutExercises, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutExercisesRow{}
	for rows.Next() {
		var i ListWorkoutExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.Sets,
			&i.TargetReps,
			&i.TargetDurationSeconds,
			&i.RestSeconds,
			&i.SortOrder,
			&i.Notes,
			&i.ExerciseName,
			&i.ExerciseSlug,
			&i.ExerciseDifficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
