import { Navigate, Route, Routes } from 'react-router-dom'
import { AppLayout } from './shell'
import { PlaceholderPage } from '../pages/placeholder'
import { HomePage } from '../pages/home'
import { LessonPage, LessonsPage } from '../pages/lessons'
import { ExercisePage, ExercisesPage } from '../pages/exercises'
import { WorkoutCatalogPage, WorkoutPlayerPage, WorkoutPreviewPage } from '../pages/workout'
import { ProgressPage } from '../pages/progress'
import { AchievementsPage } from '../pages/achievements'
import { AdminPage } from '../pages/admin'
export function AppRouter() { return <Routes><Route element={<AppLayout />}><Route index element={<HomePage />} /><Route path="lessons" element={<LessonsPage />} /><Route path="lessons/:id" element={<LessonPage />} /><Route path="exercises" element={<ExercisesPage />} /><Route path="exercises/:id" element={<ExercisePage />} /><Route path="workouts" element={<WorkoutCatalogPage />} /><Route path="workouts/:id" element={<WorkoutPreviewPage />} /><Route path="workout-session/:id" element={<WorkoutPlayerPage />} /><Route path="workout/today" element={<Navigate to="/workouts" replace />} /><Route path="progress" element={<ProgressPage />} /><Route path="achievements" element={<AchievementsPage />} /><Route path="admin" element={<AdminPage />} /><Route path="profile" element={<PlaceholderPage title="Профиль" text="Настройки профиля будут доступны после завершения авторизации." />} /><Route path="*" element={<Navigate to="/" replace />} /></Route></Routes> }
