DROP INDEX IF EXISTS idx_media_assets_owner_created;
DROP INDEX IF EXISTS idx_skills_owner_status;
DROP INDEX IF EXISTS idx_workouts_owner_status;
DROP INDEX IF EXISTS idx_programs_owner_status;
DROP INDEX IF EXISTS idx_exercises_owner_status;
DROP INDEX IF EXISTS idx_lessons_owner_status;
DROP TRIGGER IF EXISTS programs_sync_lifecycle ON programs;
DROP TRIGGER IF EXISTS lessons_sync_lifecycle ON lessons;
DROP TRIGGER IF EXISTS media_assets_set_updated_at ON media_assets;
DROP FUNCTION IF EXISTS sync_content_lifecycle();
UPDATE skill_levels SET criterion_type='manual_confirmation' WHERE criterion_type NOT IN ('workout_completed','duration_seconds','repetitions','manual_confirmation');
UPDATE skills SET final_criterion_type='manual_confirmation' WHERE final_criterion_type NOT IN ('duration_seconds','repetitions','manual_confirmation');
ALTER TABLE skill_levels DROP CONSTRAINT skill_levels_criterion_type_check;
ALTER TABLE skill_levels ADD CONSTRAINT skill_levels_criterion_type_check CHECK (criterion_type IN ('workout_completed','duration_seconds','repetitions','manual_confirmation'));
ALTER TABLE skills DROP CONSTRAINT skills_final_criterion_type_check;
ALTER TABLE skills ADD CONSTRAINT skills_final_criterion_type_check CHECK (final_criterion_type IN ('duration_seconds','repetitions','manual_confirmation'));
ALTER TABLE skills DROP COLUMN published_by,DROP COLUMN published_at,DROP COLUMN cover_media_id,DROP COLUMN status,DROP COLUMN owner_user_id;
ALTER TABLE workouts DROP COLUMN published_by,DROP COLUMN published_at,DROP COLUMN cover_media_id,DROP COLUMN status,DROP COLUMN owner_user_id;
ALTER TABLE programs DROP COLUMN published_by,DROP COLUMN published_at,DROP COLUMN coach_description,DROP COLUMN cover_media_id,DROP COLUMN status,DROP COLUMN owner_user_id;
ALTER TABLE exercises DROP COLUMN published_by,DROP COLUMN published_at,DROP COLUMN cover_media_id,DROP COLUMN coach_tips,DROP COLUMN movement_type,DROP COLUMN status,DROP COLUMN owner_user_id;
ALTER TABLE lessons DROP COLUMN published_by,DROP COLUMN published_at,DROP COLUMN cover_media_id,DROP COLUMN content_blocks,DROP COLUMN status,DROP COLUMN owner_user_id;
DROP TABLE media_assets;
UPDATE admin_users SET role='admin' WHERE role='coach';
ALTER TABLE admin_users DROP CONSTRAINT admin_users_role_check;
ALTER TABLE admin_users ADD CONSTRAINT admin_users_role_check CHECK (role IN ('admin','super_admin'));
