ALTER TABLE admin_users DROP CONSTRAINT admin_users_role_check;
ALTER TABLE admin_users ADD CONSTRAINT admin_users_role_check CHECK (role IN ('coach','admin','super_admin'));
DROP TRIGGER IF EXISTS media_assign_tenant ON media_assets;
DROP TRIGGER IF EXISTS skills_assign_tenant ON skills;
DROP TRIGGER IF EXISTS workouts_assign_tenant ON workouts;
DROP TRIGGER IF EXISTS programs_assign_tenant ON programs;
DROP TRIGGER IF EXISTS exercises_assign_tenant ON exercises;
DROP TRIGGER IF EXISTS lessons_assign_tenant ON lessons;
DROP FUNCTION IF EXISTS assign_content_tenant();
DROP TRIGGER IF EXISTS skill_requirements_tenant_guard ON skill_requirements;
DROP TRIGGER IF EXISTS skills_media_tenant_guard ON skills;
DROP TRIGGER IF EXISTS programs_media_tenant_guard ON programs;
DROP TRIGGER IF EXISTS workouts_media_tenant_guard ON workouts;
DROP TRIGGER IF EXISTS exercises_media_tenant_guard ON exercises;
DROP TRIGGER IF EXISTS lessons_media_tenant_guard ON lessons;
DROP FUNCTION IF EXISTS enforce_content_media_tenant();
DROP TRIGGER IF EXISTS skill_levels_tenant_guard ON skill_levels;
DROP TRIGGER IF EXISTS exercise_sets_tenant_guard ON exercise_sets;
DROP TRIGGER IF EXISTS planned_tenant_guard ON user_planned_workouts;
DROP TRIGGER IF EXISTS schedules_tenant_guard ON user_training_schedules;
DROP TRIGGER IF EXISTS workout_sessions_tenant_guard ON workout_sessions;
DROP TRIGGER IF EXISTS workouts_tenant_guard ON workouts;
DROP TRIGGER IF EXISTS workout_exercises_tenant_guard ON workout_exercises;
DROP FUNCTION IF EXISTS enforce_tenant_references();
ALTER TABLE user_program_progress DROP CONSTRAINT user_program_progress_pkey;
DROP INDEX IF EXISTS user_program_progress_legacy_conflict;
ALTER TABLE user_program_progress ADD PRIMARY KEY(user_id,program_id);
ALTER TABLE user_exercise_stats DROP CONSTRAINT IF EXISTS user_exercise_stats_pkey;
DROP INDEX IF EXISTS user_exercise_stats_tenant_key;
ALTER TABLE user_exercise_stats DROP COLUMN tenant_id;
ALTER TABLE user_exercise_stats ADD PRIMARY KEY(user_id,exercise_id);
ALTER TABLE user_planned_workouts DROP COLUMN tenant_id;
ALTER TABLE user_training_schedules DROP COLUMN tenant_id;
ALTER TABLE user_lesson_progress DROP COLUMN tenant_id;
ALTER TABLE user_skill_criteria DROP COLUMN tenant_id;
ALTER TABLE user_skill_level_progress DROP COLUMN tenant_id;
ALTER TABLE user_skill_progress DROP COLUMN tenant_id;
ALTER TABLE user_program_progress DROP COLUMN tenant_id;
ALTER TABLE workout_sessions DROP COLUMN tenant_id;
ALTER TABLE media_assets DROP CONSTRAINT media_tenant_owned, DROP COLUMN tenant_id;
ALTER TABLE skills DROP CONSTRAINT skills_tenant_owned, DROP COLUMN tenant_id;
ALTER TABLE workouts DROP CONSTRAINT workouts_tenant_owned, DROP COLUMN tenant_id;
ALTER TABLE programs DROP CONSTRAINT programs_tenant_owned, DROP COLUMN tenant_id;
ALTER TABLE exercises DROP CONSTRAINT exercises_global_or_tenant, DROP COLUMN tenant_id;
ALTER TABLE lessons DROP CONSTRAINT lessons_tenant_owned, DROP COLUMN tenant_id;
DROP TABLE tenant_memberships;
DROP TABLE tenants;
