// @vitest-environment jsdom
import {cleanup,render,screen,within} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {MemoryRouter} from 'react-router-dom'
import {afterEach,describe,expect,it,vi} from 'vitest'
import type {BuilderInput,CoachOptions} from '../api/coach'
import {WorkoutFields} from './coachAuthoring'
import {estimateWorkoutMinutes,filterExerciseOptions,moveWorkoutExercise} from './WorkoutBuilderFields'

afterEach(()=>{cleanup();vi.restoreAllMocks()})
const base:BuilderInput={title:'Тест',description:'План',difficulty:'beginner',category:'strength',estimated_minutes:20,warmup_enabled:true,exercises:[]}
const exercises:CoachOptions['exercises']=[
  {id:'10000000-0000-0000-0000-000000000001',name:'Отжимания',status:'published',difficulty:'beginner',description:'Жим от пола',movement_type:'reps',muscle_groups:['chest'],equipment:['floor'],tags:['push']},
  {id:'10000000-0000-0000-0000-000000000002',name:'Планка',status:'published',difficulty:'intermediate',description:'Удержание корпуса',movement_type:'duration',muscle_groups:['core'],equipment:['floor'],tags:['core'],owner_user_id:'90000000-0000-0000-0000-000000000001'},
]
const opts:CoachOptions={categories:[],exercises,programs:[],program_levels:[],workouts:[],warmups:[{id:'59000000-0000-0000-0000-000000000001',name:'Полная разминка',status:'published',minutes:8,exercise_count:5}],skills:[],media:[]}
function view(value=base,change=vi.fn(),options=opts){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return {change,...render(<QueryClientProvider client={client}><MemoryRouter><WorkoutFields value={value} change={change} opts={options}/></MemoryRouter></QueryClientProvider>)}}

describe('Coach Workout Builder',()=>{
  it('keeps workout standalone and configures warmup',async()=>{const {change}=view();expect(screen.getByLabelText('Разминка перед тренировкой')).toBeTruthy();expect(screen.queryByText('Этап программы')).toBeNull();await userEvent.selectOptions(screen.getByRole('combobox'),'59000000-0000-0000-0000-000000000001');expect(change).toHaveBeenLastCalledWith(expect.objectContaining({warmup_workout_id:opts.warmups[0].id}))})
  it('searches and adds multiple system/own exercises',async()=>{const {change}=view();await userEvent.click(screen.getByText('+ Добавить упражнение'));const picker=screen.getByRole('dialog',{name:'Выбор упражнений'});expect(within(picker).getByText('Стандартное')).toBeTruthy();expect(within(picker).getByText('Моё')).toBeTruthy();await userEvent.type(within(picker).getByPlaceholderText('Поиск упражнения...'),'план');expect(within(picker).queryByText('Отжимания')).toBeNull();await userEvent.clear(within(picker).getByPlaceholderText('Поиск упражнения...'));for(const button of within(picker).getAllByText('Добавить'))await userEvent.click(button);expect(within(picker).getByText('Выбрано: 2')).toBeTruthy();await userEvent.click(within(picker).getByText('Добавить 2 упражнений'));expect(change).toHaveBeenCalledWith(expect.objectContaining({exercises:[expect.objectContaining({exercise_id:exercises[0].id,target_reps:10}),expect.objectContaining({exercise_id:exercises[1].id,target_duration_seconds:30})]}))})
  it('opens exercise detail',async()=>{view();await userEvent.click(screen.getByText('+ Добавить упражнение'));await userEvent.click(screen.getByText('Отжимания'));const detail=screen.getByRole('dialog',{name:'Описание упражнения'});expect(within(detail).getByText('Жим от пола')).toBeTruthy();expect(within(detail).getByText(/Грудь/)).toBeTruthy()})
  it('supports empty numeric input, timed override, reorder and removal',async()=>{const change=vi.fn();const value={...base,exercises:[{exercise_id:exercises[0].id,sets:3,target_reps:10,rest_seconds:60,sort_order:0},{exercise_id:exercises[1].id,sets:3,target_duration_seconds:30,rest_seconds:45,sort_order:1}]};view(value,change);await userEvent.clear(screen.getAllByLabelText('Подходы')[0]);expect(change).toHaveBeenCalledWith(expect.objectContaining({exercises:expect.arrayContaining([expect.objectContaining({sets:undefined})])}));await userEvent.click(screen.getAllByText('Время')[0]);expect(change).toHaveBeenCalledWith(expect.objectContaining({exercises:expect.arrayContaining([expect.objectContaining({target_reps:undefined,target_duration_seconds:30})])}));await userEvent.click(screen.getAllByText('↑ Выше')[1]);expect(change).toHaveBeenCalledWith(expect.objectContaining({exercises:[expect.objectContaining({exercise_id:exercises[1].id,sort_order:0}),expect.objectContaining({exercise_id:exercises[0].id,sort_order:1})]}));vi.spyOn(window,'confirm').mockReturnValue(true);await userEvent.click(screen.getAllByText('Удалить')[0]);expect(change).toHaveBeenCalledWith(expect.objectContaining({exercises:[expect.objectContaining({exercise_id:exercises[1].id})]}))})
  it('renders student preview outline',async()=>{view({...base,exercises:[{exercise_id:exercises[0].id,sets:3,target_reps:10,rest_seconds:45,sort_order:0}]});await userEvent.click(screen.getByText('Предпросмотр тренировки'));expect(within(screen.getByRole('dialog',{name:'Предпросмотр тренировки'})).getByText('3×10 · отдых 45 сек')).toBeTruthy()})
})

it('handles a production-size lightweight catalog',()=>{const catalog=Array.from({length:300},(_,i)=>({...exercises[i%2],id:String(i),name:`Упражнение ${i}`}));expect(filterExerciseOptions(catalog,{search:'упражнение',difficulty:'beginner',type:'reps',equipment:'floor',direction:'push',muscle:'chest',ownership:'system'})).toHaveLength(150);const items=[{exercise_id:'a',sets:3,target_reps:10,rest_seconds:60,sort_order:0},{exercise_id:'b',sets:3,target_duration_seconds:30,rest_seconds:45,sort_order:1}];expect(moveWorkoutExercise(items,1,-1).map(x=>[x.exercise_id,x.sort_order])).toEqual([['b',0],['a',1]]);expect(estimateWorkoutMinutes(items)).toBeGreaterThan(0)})
