import {useQuery} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {getToday,occurrenceRoute} from '../api/calendar'
import {listPrograms} from '../api/programs'
import {getProgress} from '../api/progress'
import {listSkills} from '../api/skills'
import {listWorkouts} from '../api/workouts'
import {useSessionStore} from '../store/session'

export function HomePage(){
  const user=useSessionStore(s=>s.user),token=useSessionStore(s=>s.accessToken)
  const skills=useQuery({queryKey:['home-skills'],queryFn:()=>listSkills(token!),enabled:!!token}),today=useQuery({queryKey:['calendar-today'],queryFn:()=>getToday(token!),enabled:!!token}),programs=useQuery({queryKey:['home-programs'],queryFn:()=>listPrograms(token!),enabled:!!token}),workouts=useQuery({queryKey:['home-workouts'],queryFn:()=>listWorkouts(token!),enabled:!!token}),progress=useQuery({queryKey:['home-progress'],queryFn:()=>getProgress(token!),enabled:!!token})
  const activeSession=workouts.data?.workouts.find(x=>x.status==='started'&&x.active_session_id),activeProgram=programs.data?.programs.find(x=>x.progress_status==='active'),planned=(today.data?.occurrences??[]).filter(x=>x.status==='scheduled'),mastered=skills.data?.skills.filter(x=>x.status==='mastered').length??0
  return <div className="stack student-home">
    {user?.current_tenant&&<section className="card tenant-context"><p className="eyebrow">ВАША ШКОЛА</p><div className="tenant-brand">{user.current_tenant.avatar_url?<img className="tenant-avatar" src={user.current_tenant.avatar_url} alt=""/>:<span className="tenant-avatar tenant-avatar-fallback">{user.current_tenant.avatar_initials}</span>}<h2>{user.current_tenant.name}</h2></div>{user.current_tenant.description&&<p>{user.current_tenant.description}</p>}</section>}
    <section className="home-identity">{user?.photo_url?<img src={user.photo_url} alt=""/>:<span>{user?.display_name?.slice(0,1)??'А'}</span>}<div><b>{user?.display_name}</b><small>Уровень {user?.level??1} · {user?.xp??0} XP · 🔥 {user?.current_streak??0}</small></div></section>
    {(activeSession||activeProgram)&&<section className="hero-card continue-card"><p className="eyebrow">ПРОДОЛЖИТЬ</p>{activeSession?<><h2>Продолжить тренировку</h2><p>{activeSession.title}</p><Link className="primary-button" to={`/workout-session/${activeSession.active_session_id}`}>Продолжить</Link></>:<><h2>{activeProgram?.name}</h2><p>{activeProgram?.current_stage}</p><Link className="primary-button" to={activeProgram?.next_workout?`/workouts/${activeProgram.next_workout.id}`:`/programs/${activeProgram?.id}`}>Продолжить программу</Link></>}</section>}
    <section className="card today-card"><p className="eyebrow">КАЛЕНДАРЬ</p><div className="calendar-week-strip" aria-label="Текущая неделя">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((day,index)=><span className={index===(new Date().getDay()+6)%7?'today':''} key={day}>{day}</span>)}</div>{planned.length?planned.slice(0,2).map(x=><div className="today-row" key={x.planned_workout_id??x.workout_id}><span><b>{x.time??'Сегодня'}</b>{x.workout_title}<small>{x.estimated_minutes} мин</small></span><Link to={occurrenceRoute(x)}>Начать</Link></div>):<p className="muted">На сегодня ничего не запланировано</p>}<Link className="text-link" to="/calendar">Открыть календарь</Link></section>
    <section className="metric-grid home-summary"><article><b>{mastered}</b><span>навыков освоено</span></article><article><b>{programs.data?.programs.filter(x=>x.progress_status==='active').length??0}</b><span>активных программ</span></article><article><b>{progress.data?.total_workouts??0}</b><span>тренировок</span></article></section>
    <section className="card stack"><div className="section-heading"><div><p className="eyebrow">ТРЕНИРОВКИ</p><h3>Что тренируем?</h3></div><Link to="/workouts">Все →</Link></div><div className="training-categories home-categories"><Link to="/workouts?category=warmup">Разминка</Link><Link to="/workouts?category=morning">Зарядка</Link><Link to="/workouts?category=strength">Сила</Link><Link to="/workouts?category=skill">Навыки</Link></div></section>
    <section className="stack"><div className="section-heading"><div><p className="eyebrow">ПРОГРАММЫ</p><h3>Выберите путь</h3></div><Link to="/programs">Смотреть все →</Link></div>{programs.data?.programs.slice(0,3).map(p=><Link className={`workout-card${p.cover_media_url?' has-cover':''}`} to={`/programs/${p.id}`} key={p.id}>{p.cover_media_url&&<img className="workout-card-cover" src={p.cover_media_url} alt="" loading="lazy"/>}<div><p className="eyebrow">{p.difficulty} · {p.duration_weeks} недель</p><h3>{p.name}</h3></div><footer><b>{p.workout_count} тренировок</b></footer></Link>)}{programs.isSuccess&&!programs.data.programs.length&&<div className="empty-state compact">Опубликованных программ пока нет.</div>}</section>
    <section className="card stack"><div className="section-heading"><div><p className="eyebrow">НАВЫКИ</p><h3>Карта развития</h3></div><Link to="/skills">Открыть →</Link></div><div className="skill-category-preview"><span>Базовые</span><span>Пол</span><span>Турник</span><span>Брусья</span></div></section>
  </div>
}
