// @vitest-environment jsdom
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {cleanup,render,screen} from '@testing-library/react'
import {MemoryRouter} from 'react-router-dom'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {useSessionStore} from '../store/session'
import {HomePage} from './home'
const mocks=vi.hoisted(()=>({listPrograms:vi.fn(),listSkills:vi.fn(),getToday:vi.fn(),listWorkouts:vi.fn(),getProgress:vi.fn()}))
vi.mock('../api/programs',()=>({listPrograms:mocks.listPrograms}))
vi.mock('../api/skills',()=>({listSkills:mocks.listSkills}))
vi.mock('../api/calendar',()=>({getToday:mocks.getToday,occurrenceRoute:vi.fn()}))
vi.mock('../api/workouts',()=>({listWorkouts:mocks.listWorkouts}))
vi.mock('../api/progress',()=>({getProgress:mocks.getProgress}))
beforeEach(()=>{useSessionStore.setState({accessToken:'token',status:'authenticated',user:{id:'u',display_name:'Анна',first_name:'Анна',level:2,xp:120,current_streak:3,timezone:'UTC',role:'user',available_modes:['student']}});mocks.listSkills.mockResolvedValue({skills:[]});mocks.getToday.mockResolvedValue({occurrences:[]});mocks.listWorkouts.mockResolvedValue({workouts:[]});mocks.getProgress.mockResolvedValue({total_workouts:7});mocks.listPrograms.mockResolvedValue({programs:[{id:'40000000-0000-0000-0000-000000000001',name:'Базовая сила',difficulty:'beginner',duration_weeks:4,workout_count:4}]})})
afterEach(cleanup)
describe('student home programs',()=>{it('places a compact program preview after the workouts entry',async()=>{render(<QueryClientProvider client={new QueryClient()}><MemoryRouter><HomePage/></MemoryRouter></QueryClientProvider>);const training=screen.getByText('ТРЕНИРОВКИ');const programs=await screen.findByText('ПРОГРАММЫ');expect(training.compareDocumentPosition(programs)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect((await screen.findByText('Базовая сила')).closest('a')?.getAttribute('href')).toBe('/programs/40000000-0000-0000-0000-000000000001');expect(screen.getByText('Смотреть все →').closest('a')?.getAttribute('href')).toBe('/programs')});it('prioritizes an active workout session',async()=>{mocks.listWorkouts.mockResolvedValue({workouts:[{id:'w',title:'Горизонт',status:'started',active_session_id:'70000000-0000-0000-0000-000000000001'}]});render(<QueryClientProvider client={new QueryClient()}><MemoryRouter><HomePage/></MemoryRouter></QueryClientProvider>);expect(await screen.findByText('Продолжить тренировку')).toBeTruthy();expect(screen.getByText('Продолжить').closest('a')?.getAttribute('href')).toContain('/workout-session/')});it('shows only current tenant branding and hides an empty description',async()=>{useSessionStore.setState(state=>({user:{...state.user!,current_tenant:{id:'a',slug:'a',name:'Школа A',role:'student',description:'Описание A'},tenants:[{id:'b',slug:'b',name:'Школа B',role:'student',description:'Описание B'}]}}));const {rerender}=render(<QueryClientProvider client={new QueryClient()}><MemoryRouter><HomePage/></MemoryRouter></QueryClientProvider>);expect(screen.getByText('Описание A')).toBeTruthy();expect(screen.queryByText('Описание B')).toBeNull();useSessionStore.setState(state=>({user:{...state.user!,current_tenant:{id:'b',slug:'b',name:'Школа B',role:'student',description:''}}}));rerender(<QueryClientProvider client={new QueryClient()}><MemoryRouter><HomePage/></MemoryRouter></QueryClientProvider>);expect(screen.getByText('Школа B')).toBeTruthy();expect(screen.queryByText('Описание A')).toBeNull()})})
