import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { completeLesson, getLesson, listLessons } from '../api/lessons'
import type { LessonBlock } from '../api/lessons'
import { isValidEntityID, lessonRoute } from '../api/entityIds'
import { useSessionStore } from '../store/session'
import '../lessonContent.css'

export function LessonsPage(){const token=useSessionStore(s=>s.accessToken);const query=useQuery({queryKey:['lessons'],queryFn:()=>listLessons(token!),enabled:Boolean(token)});if(!token)return <LessonNotice/>;if(query.isLoading)return <div className="notice skeleton">Загружаем уроки…</div>;if(query.isError)return <div className="notice error">Не удалось загрузить уроки.</div>;return <div className="stack"><h2>Уроки</h2>{query.data?.lessons.map(l=>{const route=lessonRoute(l.id);return route?<Link className="lesson-card" key={l.id} to={route}><div><p className="eyebrow">{l.category_name} · {l.difficulty}</p><h3>{l.title}</h3><p>{l.short_description}</p></div><aside><b>{l.duration_minutes} мин</b><span>{l.completed?'✓ Готово':'Начать'}</span></aside></Link>:<div className="notice error" key={l.title}>Урок «{l.title}» недоступен: отсутствует корректный ID.</div>})}</div>}
export function LessonPage(){const {id=''}=useParams();const validID=isValidEntityID(id);const token=useSessionStore(s=>s.accessToken);const client=useQueryClient();const query=useQuery({queryKey:['lesson',id],queryFn:()=>getLesson(token!,id),enabled:Boolean(token&&validID)});const mutation=useMutation({mutationFn:()=>completeLesson(token!,id),onSuccess:()=>client.invalidateQueries({queryKey:['lessons']})});if(!token)return <LessonNotice/>;if(!validID)return <div className="notice error">Некорректный идентификатор урока.</div>;if(query.isLoading)return <div className="notice skeleton">Загружаем урок…</div>;if(query.isError||!query.data)return <div className="notice error">Урок не найден.</div>;const lesson=query.data.lesson;return <article className="stack lesson-detail"><Link className="text-link" to="/lessons">← Все уроки</Link>{lesson.cover_media_url&&<img className="lesson-cover" src={lesson.cover_media_url} alt=""/>}<p className="eyebrow">{lesson.category_name} · {lesson.duration_minutes} мин</p><h2>{lesson.title}</h2>{lesson.short_description&&<p className="lead">{lesson.short_description}</p>}<div className="lesson-blocks">{lesson.content_blocks?.length?lesson.content_blocks.map((block,index)=><LessonContentBlock block={block} key={index}/>):lesson.content&&<div className="card lesson-content">{lesson.content}</div>}</div><button className="primary-button" disabled={lesson.completed||mutation.isPending} onClick={()=>mutation.mutate()}>{lesson.completed?'Урок завершён':mutation.isPending?'Сохраняем…':'Завершить урок · +20 XP'}</button>{mutation.isSuccess&&<p className="success">{mutation.data.already_completed?'Урок уже был завершён.':`Готово! +${mutation.data.xp_earned} XP`}</p>}</article>}
function LessonContentBlock({block}:{block:LessonBlock}){if(block.type==='divider')return <hr/>;if(block.type==='heading')return <h3>{block.text}</h3>;if(block.type==='image')return block.url?<figure><img src={block.url} alt={block.alt??''}/>{block.text&&<figcaption>{block.text}</figcaption>}</figure>:null;if(block.type==='video')return block.url?<video controls preload="metadata" src={block.url}/>:null;if(block.type==='checklist')return <ul className="lesson-checklist">{block.items?.map((item,i)=><li key={i}>{item}</li>)}</ul>;if(block.type==='tip'||block.type==='warning')return <aside className={`lesson-callout ${block.type}`}><b>{block.type==='tip'?'Совет тренера':'Важно'}</b><p>{block.text}</p></aside>;return <p className="lesson-text">{block.text}</p>}
function LessonNotice(){return <div className="empty-state"><div className="empty-icon">✦</div><h2>Уроки доступны в Telegram</h2><p>Для синхронизации прогресса откройте приложение из Telegram.</p></div>}
