// @vitest-environment jsdom
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {cleanup,render,screen,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import type {ReactNode} from 'react'
import {MemoryRouter,Route,Routes} from 'react-router-dom'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {useSessionStore} from '../store/session'
import {canonicalCategory,WorkoutCatalogPage,WorkoutPlayerRoute,WorkoutPreviewPage} from './workout'

const mocks=vi.hoisted(()=>({listWorkouts:vi.fn(),getWorkout:vi.fn(),getSession:vi.fn(),start:vi.fn(),saveSet:vi.fn(),complete:vi.fn()}))
vi.mock('../api/workouts',async importOriginal=>({...await importOriginal<typeof import('../api/workouts')>(),...mocks}))
vi.mock('../api/programs',()=>({listPrograms:vi.fn().mockResolvedValue({programs:[]})}))
vi.mock('../api/skills',()=>({listSkills:vi.fn().mockResolvedValue({skills:[]})}))
const workout={id:'50000000-0000-0000-0000-000000000001',title:'Стойка на руках — уровень 1',description:'Подготовительная тренировка',estimated_minutes:30,difficulty:'beginner',program_id:'40000000-0000-0000-0000-000000000001',program_name:'Путь к стойке на руках',exercises:[{id:'30000000-0000-0000-0000-000000000001',name:'Hollow Body Hold',sets:3,target_duration_seconds:20,rest_seconds:45}]}
const wrapper=(ui:ReactNode,path='/workouts')=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><MemoryRouter initialEntries={[path]}>{ui}</MemoryRouter></QueryClientProvider>)

beforeEach(()=>{useSessionStore.setState({accessToken:'token',status:'authenticated'});vi.clearAllMocks();vi.spyOn(HTMLMediaElement.prototype,'play').mockResolvedValue()})
afterEach(cleanup)

describe('workout pages',()=>{
  it('normalizes all legacy categories into the four public categories',()=>{expect(['WARMUP','MORNING_ROUTINE','BASE_STRENGTH','SKILL','MOBILITY','OTHER'].map(canonicalCategory)).toEqual(['warmup','morning','strength','skill','warmup','strength'])})
  it('renders the workout catalog without starting a session',async()=>{mocks.listWorkouts.mockResolvedValue({workouts:[{...workout,exercise_count:8,status:'completed'}]});wrapper(<WorkoutCatalogPage/>);const title=await screen.findByText(workout.title);expect(title.closest('a')?.getAttribute('href')).toBe(`/workouts/${workout.id}`);expect(screen.getByText('8 упр.')).toBeTruthy();expect(mocks.start).not.toHaveBeenCalled()})
  it('renders preview and starts only after the button click',async()=>{mocks.getWorkout.mockResolvedValue({workout});mocks.start.mockResolvedValue({session:{id:'70000000-0000-0000-0000-000000000001'}});wrapper(<Routes><Route path="/workouts/:id" element={<WorkoutPreviewPage/>}/><Route path="/workout-session/:id" element={<p>Active player</p>}/></Routes>,`/workouts/${workout.id}`);expect(await screen.findByText('Hollow Body Hold')).toBeTruthy();expect(mocks.start).not.toHaveBeenCalled();await userEvent.click(screen.getByRole('button',{name:'Начать тренировку'}));await waitFor(()=>expect(mocks.start).toHaveBeenCalledTimes(1));expect(await screen.findByText('Active player')).toBeTruthy()})
  it('offers the reusable default warmup and starts it before the main session',async()=>{const warmup={id:'50000000-0000-0000-0000-000000000099',title:'Полная разминка',estimated_minutes:12};mocks.getWorkout.mockResolvedValue({workout:{...workout,warmup_enabled:true,default_warmup:warmup}});mocks.start.mockResolvedValue({session:{id:'70000000-0000-0000-0000-000000000001'}});wrapper(<Routes><Route path="/workouts/:id" element={<WorkoutPreviewPage/>}/><Route path="/workout-session/:id" element={<p>Warmup player</p>}/></Routes>,`/workouts/${workout.id}`);expect(await screen.findByText('Полная разминка')).toBeTruthy();await userEvent.click(screen.getByRole('button',{name:'Начать с разминки'}));await waitFor(()=>expect(mocks.start).toHaveBeenCalledWith('token',warmup.id,{follow_up_workout_id:workout.id}));expect(await screen.findByText('Warmup player')).toBeTruthy()})
  it('can skip an enabled warmup and start the main workout directly',async()=>{mocks.getWorkout.mockResolvedValue({workout:{...workout,warmup_enabled:true,default_warmup:{id:'50000000-0000-0000-0000-000000000099',title:'Разминка',estimated_minutes:10}}});mocks.start.mockResolvedValue({session:{id:'70000000-0000-0000-0000-000000000001'}});wrapper(<Routes><Route path="/workouts/:id" element={<WorkoutPreviewPage/>}/><Route path="/workout-session/:id" element={<p>Main player</p>}/></Routes>,`/workouts/${workout.id}`);await userEvent.click(await screen.findByRole('button',{name:'Начать без разминки'}));await waitFor(()=>expect(mocks.start).toHaveBeenCalledWith('token',workout.id,{}));expect(await screen.findByText('Main player')).toBeTruthy()})
  it('shows an API failure and prevents duplicate clicks while pending',async()=>{mocks.getWorkout.mockResolvedValue({workout});let reject!:(error:Error)=>void;mocks.start.mockReturnValue(new Promise((_,r)=>{reject=r}));wrapper(<Routes><Route path="/workouts/:id" element={<WorkoutPreviewPage/>}/></Routes>,`/workouts/${workout.id}`);const button=await screen.findByRole('button',{name:'Начать тренировку'}) as HTMLButtonElement;await userEvent.click(button);expect(button.disabled).toBe(true);await userEvent.click(button);expect(mocks.start).toHaveBeenCalledTimes(1);reject(new Error('API unavailable'));expect(await screen.findByText('API unavailable')).toBeTruthy()})
  it('remounts the player on persisted warmup continuation and opens the main session',async()=>{const warmupSession='70000000-0000-0000-0000-000000000001',mainSession='70000000-0000-0000-0000-000000000002';mocks.getSession.mockImplementation(async(_token:string,id:string)=>id===warmupSession?{session:{id:warmupSession,workout_id:'59000000-0000-0000-0000-000000000001',status:'completed',started_at:new Date().toISOString(),duration_seconds:60,xp_earned:0,continued_session_id:mainSession,follow_up_workout_title:'Корпус и ноги'},workout:{...workout,id:'59000000-0000-0000-0000-000000000001',title:'Полная разминка'},completed_sets:[]}:{session:{id:mainSession,workout_id:workout.id,status:'started',started_at:new Date().toISOString(),duration_seconds:0,xp_earned:0},workout:{...workout,title:'Корпус и ноги'},completed_sets:[]});wrapper(<Routes><Route path="/workout-session/:id" element={<WorkoutPlayerRoute/>}/></Routes>,`/workout-session/${warmupSession}`);expect(await screen.findByText('РАЗМИНКА ЗАВЕРШЕНА')).toBeTruthy();expect(await screen.findByText('АКТИВНАЯ ТРЕНИРОВКА')).toBeTruthy();expect(mocks.getSession).toHaveBeenCalledWith('token',mainSession);expect(mocks.start).not.toHaveBeenCalled()})
  it('labels completed warmup action as transition to the main workout',async()=>{const sessionID='70000000-0000-0000-0000-000000000001';mocks.getSession.mockResolvedValue({session:{id:sessionID,workout_id:workout.id,status:'started',started_at:new Date().toISOString(),duration_seconds:0,xp_earned:0,session_purpose:'warmup',follow_up_workout_id:'50000000-0000-0000-0000-000000000002'},workout:{...workout,exercises:[workout.exercises[0]]},completed_sets:[1,2,3].map(set_number=>({exercise_id:workout.exercises[0].id,set_number,duration_seconds:20,completed:true}))});wrapper(<Routes><Route path="/workout-session/:id" element={<WorkoutPlayerRoute/>}/></Routes>,`/workout-session/${sessionID}`);expect(await screen.findByRole('button',{name:'Перейти к тренировке'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Завершить тренировку'})).toBeNull()})
  it('shows demo media while the voice introduction and preparation are active',async()=>{const sessionID='70000000-0000-0000-0000-000000000003';const exercise={...workout.exercises[0],target_duration_seconds:undefined,target_reps:8,demo_media_url:'https://example.com/demo.mp4',demo_media_type:'video' as const,demo_media_mime_type:'video/mp4'};mocks.getSession.mockResolvedValue({session:{id:sessionID,workout_id:workout.id,status:'started',started_at:new Date().toISOString(),duration_seconds:0,xp_earned:0},workout:{...workout,exercises:[exercise]},completed_sets:[]});wrapper(<Routes><Route path="/workout-session/:id" element={<WorkoutPlayerRoute/>}/></Routes>,`/workout-session/${sessionID}`);expect(await screen.findByLabelText('Демонстрация упражнения')).toBeTruthy();expect(screen.getByText(/подсказку|Приготовьтесь/)).toBeTruthy()})
})
